package com.myjava.learn;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

import com.myjava.quanlycuahang.UTIL.JDBCUtil;

/**
 *
 * @author truon
 */
public class BtTXSSinhVien extends javax.swing.JFrame {

    /**
     * Creates new form BtTXSSinhVien
     */
    public BtTXSSinhVien() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbDSSV = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txMaSv = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txHo = new javax.swing.JTextField();
        txTen = new javax.swing.JTextField();
        btThem = new javax.swing.JButton();
        btXoa = new javax.swing.JButton();
        btSua = new javax.swing.JButton();
        btThoat = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        rbtNam = new javax.swing.JRadioButton();
        rbtNu = new javax.swing.JRadioButton();
        rbtKhac = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        txNgsinh = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cbKhoa = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                // formMouseClicked(evt);
            }
        });

        tbDSSV.setModel(modelDSSV);
        tbDSSV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                // tbDSSVMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbDSSV);

        jLabel1.setText("Thong tin sinh vien");

        jLabel2.setText("Ma sv: ");

        jLabel3.setText("Ho: ");

        jLabel4.setText("Ten: ");

        btThem.setText("Them");
        btThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemActionPerformed(evt);
            }
        });

        btXoa.setText("Xoa");
        btXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXoaActionPerformed(evt);
            }
        });

        btSua.setText("Sua");
        btSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSuaActionPerformed(evt);
            }
        });

        btThoat.setText("Thoat");
        btThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThoatActionPerformed(evt);
            }
        });

        jLabel5.setText("Gioi tinh");

        rbtNam.setText("Nam");

        rbtNu.setText("Nu");

        rbtKhac.setText("Khac");

        jLabel6.setText("Ngay sinh");

        txNgsinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txNgsinhActionPerformed(evt);
            }
        });

        jLabel7.setText("Khoa: ");

        cbKhoa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(txNgsinh, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(56, 56, 56)
                                .addComponent(rbtNam)
                                .addGap(18, 18, 18)
                                .addComponent(rbtNu, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(rbtKhac))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txTen, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txHo, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txMaSv, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(391, 391, 391)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(291, 291, 291)
                        .addComponent(btThem)
                        .addGap(18, 18, 18)
                        .addComponent(btXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btSua, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(241, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txMaSv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txHo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(rbtNam)
                    .addComponent(rbtNu)
                    .addComponent(rbtKhac))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txNgsinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(cbKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btThem)
                    .addComponent(btXoa)
                    .addComponent(btSua)
                    .addComponent(btThoat))
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemActionPerformed
        String header[] = new String[]{"Ma SV", "Ho", "Ten", "Gioi tinh", "Ngay sinh", "Khoa"};
        if(modelDSSV.getRowCount() == 0) {
            modelDSSV = new DefaultTableModel(header, 0);
            tbDSSV.setModel(modelDSSV);
        }
        
        String gioiTinh = "";
        if(rbtNam.isSelected()) gioiTinh = "Nam";
        else if(rbtNu.isSelected()) gioiTinh = "Nu";
        else gioiTinh = "Khac";

        SinhVien sv = new SinhVien();
        sv.setMaSV(txMaSv.getText());
        sv.setHo(txHo.getText());
        sv.setTen(txTen.getText());
        sv.setGioiTinh(gioiTinh);
        sv.setNgaySinh(txNgsinh.getText());
        sv.setKhoa(cbKhoa.getSelectedItem().toString());
        listSinhVien.add(sv);

        Vector<String> data = new Vector<>();
        data.add(sv.getMaSV());
        data.add(sv.getHo());
        data.add(sv.getTen());
        data.add(sv.getGioiTinh());
        data.add(sv.getNgaySinh());
        data.add(sv.getKhoa());
        try {
            Connection conn = JDBCUtil.getConnection();
            String sql = "INSERT INTO sinhvien(masv, holot, ten, gioitinh, ngaysinh, khoa) VALUES(?, ?, ?, ?, ?, ?)";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, sv.getMaSV());
            pst.setString(2, sv.getHo());
            pst.setString(3, sv.getTen());
            pst.setString(4, sv.getGioiTinh());
            pst.setString(5, sv.getNgaySinh());
            pst.setString(6, sv.getKhoa());
            pst.executeUpdate();
        } catch (Exception e) {
            e.printStackTrace();
        }
        modelDSSV.addRow(data);
        tbDSSV.setModel(modelDSSV);
    }//GEN-LAST:event_btThemActionPerformed

    private void btXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXoaActionPerformed
        int row = tbDSSV.getSelectedRow();
        if(row >= 0) {
            try {
                Connection conn = JDBCUtil.getConnection();
                String sql = "DELETE FROM sinhvien WHERE masv = ?";
                PreparedStatement pst = conn.prepareStatement(sql);
                String masv = tbDSSV.getValueAt(row, 0).toString();
                pst.setString(1, masv);
                pst.executeUpdate();
                modelDSSV.removeRow(row);
                listSinhVien.remove(row);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btXoaActionPerformed

    private void btSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuaActionPerformed
        int row = tbDSSV.getSelectedRow();
        if(row >= 0) {
            String gioiTinh = "";
            if(rbtNam.isSelected()) gioiTinh = "Nam";
            else if(rbtNu.isSelected()) gioiTinh = "Nu";
            else gioiTinh = "Khac";

            SinhVien sv = listSinhVien.get(row);
            sv.setMaSV(txMaSv.getText());
            sv.setHo(txHo.getText());
            sv.setTen(txTen.getText());
            sv.setGioiTinh(gioiTinh);
            sv.setNgaySinh(txNgsinh.getText());
            sv.setKhoa(cbKhoa.getSelectedItem().toString());

            String sql = "UPDATE sinhvien SET holot = ?, ten = ?, gioitinh = ?, ngaysinh = ?, khoa = ? WHERE masv = ?";
            try {
                Connection conn = JDBCUtil.getConnection();
                PreparedStatement pst = conn.prepareStatement(sql);
                pst.setString(1, sv.getHo());
                pst.setString(2, sv.getTen());
                pst.setString(3, sv.getGioiTinh());
                pst.setString(4, sv.getNgaySinh());
                pst.setString(5, sv.getKhoa());
                pst.setString(6, sv.getMaSV());
                pst.executeUpdate();
            } catch (Exception e) {
                e.printStackTrace();
            }

            modelDSSV.setValueAt(sv.getMaSV(), row, 0);
            modelDSSV.setValueAt(sv.getHo(), row, 1);
            modelDSSV.setValueAt(sv.getTen(), row, 2);
            modelDSSV.setValueAt(sv.getGioiTinh(), row, 3);
            modelDSSV.setValueAt(sv.getNgaySinh(), row, 4);
            modelDSSV.setValueAt(sv.getKhoa(), row, 5);
        }
    }//GEN-LAST:event_btSuaActionPerformed

    private void btThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThoatActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btThoatActionPerformed

    private void txNgsinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txNgsinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txNgsinhActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BtTXSSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BtTXSSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BtTXSSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BtTXSSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BtTXSSinhVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSua;
    private javax.swing.JButton btThem;
    private javax.swing.JButton btThoat;
    private javax.swing.JButton btXoa;
    private javax.swing.JComboBox<String> cbKhoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbtKhac;
    private javax.swing.JRadioButton rbtNam;
    private javax.swing.JRadioButton rbtNu;
    private javax.swing.JTable tbDSSV;
    private javax.swing.JTextField txHo;
    private javax.swing.JTextField txMaSv;
    private javax.swing.JTextField txNgsinh;
    private javax.swing.JTextField txTen;
    // End of variables declaration//GEN-END:variables
    private DefaultTableModel modelDSSV;
    private javax.swing.ButtonGroup grpGioiTinh;
    private ArrayList<SinhVien> listSinhVien;
}
