package com.myjava.quanlycuahang.GUI;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

 import java.awt.event.KeyEvent;
import java.io.File;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Vector;
 
 import javax.swing.JDialog;
 import javax.swing.JFileChooser;
 import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
 import javax.swing.table.DefaultTableColumnModel;
 import javax.swing.table.DefaultTableModel;
 import javax.swing.table.TableCellRenderer;
 import javax.swing.table.TableColumn;
 import javax.swing.table.TableModel;

import com.myjava.quanlycuahang.BUS.ChucNangBUS;
import com.myjava.quanlycuahang.BUS.Constant;
import com.myjava.quanlycuahang.BUS.TaiKhoanBUS;
import com.myjava.quanlycuahang.BUS.VaiTroBUS;
import com.myjava.quanlycuahang.BUS.VaiTro_ChucNangBUS;
import com.myjava.quanlycuahang.DAO.VaiTro_ChucNangDAO;
import com.myjava.quanlycuahang.DTO.ChucNangDTO;
import com.myjava.quanlycuahang.DTO.TaiKhoanDTO;
import com.myjava.quanlycuahang.DTO.VaiTroDTO;
import com.myjava.quanlycuahang.DTO.VaiTro_ChucNangDTO;
 
 /**
  *
  * @author truon
  */
 public class DemoPhanQuyenPanel extends javax.swing.JPanel {
 
     /**
      * Creates new form DemoQLTKPanel
      */
     public DemoPhanQuyenPanel() {
         initComponents();
         updateComponents();
     }
 
     public DemoPhanQuyenPanel(JFrame frame) {
         initComponents();
         updateComponents();
         this.pFrame = frame;
     }
 
     /**
      * This method is called from within the constructor to initialize the form.
      * WARNING: Do NOT modify this code. The content of this method is always
      * regenerated by the Form Editor.
      */
     @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        chucNangPanel = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnXuatExcel = new javax.swing.JButton();
        btnNhapExcel = new javax.swing.JButton();
        timkiemPanel = new javax.swing.JPanel();
        cbFiled = new javax.swing.JComboBox<>();
        txtValueVaiTro = new javax.swing.JTextField();
        btnTimVaiTro = new javax.swing.JButton();
        btnResetBangVaiTro = new javax.swing.JButton();
        tbScrollPane = new javax.swing.JScrollPane();
        tbVaiTro = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbQuyen = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtTenQuyen = new javax.swing.JTextField();
        btnTimChucNang = new javax.swing.JButton();
        btnResetBangChucNang = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtTenVaiTro = new javax.swing.JTextField();

        setMaximumSize(new java.awt.Dimension(1200, 800));
        setMinimumSize(new java.awt.Dimension(1170, 800));

        title.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        title.setText("Quản lý phân quyền");

        chucNangPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chức năng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12))); // NOI18N

        btnThem.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXoaMouseClicked(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnSave.setText("Lưu");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnXuatExcel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnXuatExcel.setText("Xuất Excel");
        btnXuatExcel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXuatExcelMouseClicked(evt);
            }
        });

        btnNhapExcel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnNhapExcel.setText("Nhập Excel");
        btnNhapExcel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNhapExcelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout chucNangPanelLayout = new javax.swing.GroupLayout(chucNangPanel);
        chucNangPanel.setLayout(chucNangPanelLayout);
        chucNangPanelLayout.setHorizontalGroup(
            chucNangPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chucNangPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNhapExcel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnXuatExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        chucNangPanelLayout.setVerticalGroup(
            chucNangPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chucNangPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(chucNangPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnXoa)
                    .addComponent(btnSave)
                    .addComponent(btnNhapExcel)
                    .addComponent(btnXuatExcel))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        timkiemPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm kiếm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12))); // NOI18N
        timkiemPanel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        cbFiled.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txtValueVaiTro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtValueVaiTroKeyPressed(evt);
            }
        });

        btnTimVaiTro.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnTimVaiTro.setText("Tìm");
        btnTimVaiTro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTimVaiTroMouseClicked(evt);
            }
        });

        btnResetBangVaiTro.setText("Đặt lại");
        btnResetBangVaiTro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetBangVaiTroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout timkiemPanelLayout = new javax.swing.GroupLayout(timkiemPanel);
        timkiemPanel.setLayout(timkiemPanelLayout);
        timkiemPanelLayout.setHorizontalGroup(
            timkiemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timkiemPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbFiled, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtValueVaiTro, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTimVaiTro, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnResetBangVaiTro)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        timkiemPanelLayout.setVerticalGroup(
            timkiemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timkiemPanelLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(timkiemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbFiled, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValueVaiTro, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimVaiTro)
                    .addComponent(btnResetBangVaiTro))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(chucNangPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(timkiemPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(chucNangPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(timkiemPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tbVaiTro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbVaiTro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbVaiTroMouseClicked(evt);
            }
        });
        tbScrollPane.setViewportView(tbVaiTro);

        tbQuyen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tền quyền", "Thêm", "Xóa", "Sửa"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbQuyen);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Tìm chức năng:");

        txtTenQuyen.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnTimChucNang.setText("Tìm");
        btnTimChucNang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimChucNangActionPerformed(evt);
            }
        });

        btnResetBangChucNang.setText("Đặt lại");
        btnResetBangChucNang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetBangChucNangActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Tên vai trò:");

        txtTenVaiTro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tbScrollPane, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTenVaiTro, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTenQuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnTimChucNang, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnResetBangChucNang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(title)
                        .addGap(454, 454, 454))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tbScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtTenVaiTro, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnTimChucNang)
                        .addComponent(btnResetBangChucNang))
                    .addComponent(txtTenQuyen))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );
    }// </editor-fold>//GEN-END:initComponents
 
    private void btnXoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaMouseClicked
        // TODO add your handling code here:
        //TRUONG: chi duoc xoa khi ...?
        int choice = JOptionPane.showConfirmDialog(this.pFrame, "Bạn có chắc chắn muốn xóa vai trò này không?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (choice == JOptionPane.YES_OPTION) {
            int row = tbVaiTro.getSelectedRow();
            if (row < 0) {
                return;
            }
            VaiTroDTO vt = VaiTroBUS.getInstance().getList().get(row);
            try {
                VaiTro_ChucNangBUS.getInstance().xoaChucNang(vt.getMaVaiTro());//xoa cac chuc nang cua vai tro
                VaiTroBUS.getInstance().xoa(vt.getMaVaiTro()); // xoa vai tro
                JOptionPane.showMessageDialog(this.pFrame, "Xóa vai trò thành công", "Thành công", JOptionPane.INFORMATION_MESSAGE);
                tbVaiTro.clearSelection();
                updateComponents();
            } catch(Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this.pFrame, "Xóa vai trò thất bại:\n"+e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnXoaMouseClicked

    private void btnNhapExcelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNhapExcelMouseClicked
    // TODO add your handling code here:
    JFileChooser fileChooser = new JFileChooser();
    fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
    int returnValue = fileChooser.showOpenDialog(null);
    if (returnValue == JFileChooser.APPROVE_OPTION) {
        File selectedFile = fileChooser.getSelectedFile();
        String path = selectedFile.getAbsolutePath();
        System.out.println(path);
    }
    }//GEN-LAST:event_btnNhapExcelMouseClicked

    private void btnXuatExcelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXuatExcelMouseClicked
        // TODO add your handling code here:
        // JFileChooser fileChooser = new JFileChooser();
        // fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        // int returnValue = fileChooser.showSaveDialog(null); 
        // if (returnValue == JFileChooser.APPROVE_OPTION) {
        //     File selectedFile = fileChooser.getSelectedFile();
        //     String path = selectedFile.getAbsolutePath();
        //     System.out.println(path);
        // }
        

        //tao frame bao gom mot textfield va mot nut browse, nut xac nhan, nut huy
        //khi nhan nut browse, mo cua so chon file, chon file xuat excel

    }//GEN-LAST:event_btnXuatExcelMouseClicked

    private void btnTimVaiTroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTimVaiTroMouseClicked
        // TODO add your handling code here:
        String fieldName = ((MyComboboxItem)cbFiled.getSelectedItem()).getValue();
        System.out.println(fieldName);
        ArrayList<VaiTroDTO> list = VaiTroBUS.getInstance().loc(fieldName, txtValueVaiTro.getText());
        System.out.println(list.toString());
        tbModelVaiTro.setRowCount(0);
        for (VaiTroDTO vt: list) {
            Vector<String> row = new Vector<>();
            row.add(vt.getMaVaiTro()+"");
            row.add(vt.getTenVaiTro());
            tbModelVaiTro.addRow(row);
        }
    }//GEN-LAST:event_btnTimVaiTroMouseClicked

    private void txtValueVaiTroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValueVaiTroKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnTimVaiTroMouseClicked(null);
        }
    }//GEN-LAST:event_txtValueVaiTroKeyPressed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        try {
            //kiem tra neu ten vai tro trong thi khong lam gi ca
            if (txtTenVaiTro.getText().equals("")) {
                return;
            }
            int rs = 0;
            //them quyen
            rs = VaiTroBUS.getInstance().them(new VaiTroDTO(0, txtTenVaiTro.getText()));
            //them vai tro
            int maVaiTro = VaiTroBUS.getInstance().getList().get(VaiTroBUS.getInstance().getList().size()-1).getMaVaiTro();
            for (int i=0;i<tbQuyen.getRowCount();i++) {
                String maChucNang = ((ChucNangDTO)tbQuyen.getValueAt(i, 0)).getMaChucNang();
                boolean them = (boolean)tbQuyen.getValueAt(i, 1);
                boolean sua = (boolean)tbQuyen.getValueAt(i, 2);
                boolean xoa = (boolean)tbQuyen.getValueAt(i, 3);
                rs = VaiTro_ChucNangBUS.getInstance().them(new VaiTro_ChucNangDTO(maVaiTro, maChucNang, them, sua, xoa));
            }
            if (rs == 1) {
                JOptionPane.showMessageDialog(this.pFrame, "Thêm vai trò thành công", "Thành công", JOptionPane.INFORMATION_MESSAGE);
            }
            tbQuyen.clearSelection();
            updateComponents();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this.pFrame, "Thêm quyền thất bại do lỗi:\n"+e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void tbVaiTroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbVaiTroMouseClicked
        // TODO add your handling code here:
        int selected_row = tbVaiTro.getSelectedRow();
        VaiTroDTO vt = VaiTroBUS.getInstance().getList().get(selected_row);
        //hien thi ten vai tro
        txtTenVaiTro.setText(vt.getTenVaiTro());
        //thay doi bang phan quyen
        ArrayList<VaiTro_ChucNangDTO> list = VaiTro_ChucNangBUS.getInstance().getChucNang(vt.getMaVaiTro());
        for (int i=0;i<tbQuyen.getRowCount();i++) {
            String maChucNang = ((ChucNangDTO)tbQuyen.getValueAt(i, 0)).getMaChucNang();
            for (VaiTro_ChucNangDTO vtcn: list) {
                if (vtcn.getMaChucNang().equals(maChucNang)) {
                    tbQuyen.setValueAt(vtcn.getThem(), i, 1);
                    tbQuyen.setValueAt(vtcn.getSua(), i, 2);
                    tbQuyen.setValueAt(vtcn.getXoa(), i, 3);
                }
            }
        }
        tbModelQuyen.fireTableDataChanged();
        
    }//GEN-LAST:event_tbVaiTroMouseClicked

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        int selected_row = tbVaiTro.getSelectedRow();
        if (selected_row == -1) {
            return;
        }
        VaiTroDTO vt = VaiTroBUS.getInstance().getList().get(selected_row);
        try {
            int rs = 0;
            //sua ten vai tro neu khac ten cu va khac rong
            if (!vt.getTenVaiTro().equals(txtTenVaiTro.getText()) && !txtTenVaiTro.getText().equals("")) {
                rs = VaiTroBUS.getInstance().sua(new VaiTroDTO(vt.getMaVaiTro(), txtTenVaiTro.getText()));
            }
            //sua quyen
            for (int i=0;i<tbQuyen.getRowCount();i++) {
                String maChucNang = ((ChucNangDTO)tbQuyen.getValueAt(i, 0)).getMaChucNang();
                boolean them = (boolean)tbQuyen.getValueAt(i, 1);
                boolean sua = (boolean)tbQuyen.getValueAt(i, 2);
                boolean xoa = (boolean)tbQuyen.getValueAt(i, 3);
                rs = VaiTro_ChucNangBUS.getInstance().sua(new VaiTro_ChucNangDTO(vt.getMaVaiTro(), maChucNang, them, sua, xoa));
            }
            if (rs == 1) {
                JOptionPane.showMessageDialog(this.pFrame, "Sửa quyền thành công", "Thành công", JOptionPane.INFORMATION_MESSAGE);
            }
            updateComponents();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this.pFrame, "Sửa quyền thất bại do lỗi CSDL:\n"+e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnTimChucNangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimChucNangActionPerformed
        // TODO add your handling code here:
        String tenChucNang = txtTenQuyen.getText();
        ArrayList<ChucNangDTO> list = ChucNangBUS.getInstance().loc(ChucNangBUS.TENCHUCNANG, tenChucNang);
    }//GEN-LAST:event_btnTimChucNangActionPerformed

    private void btnResetBangChucNangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetBangChucNangActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnResetBangChucNangActionPerformed

    private void btnResetBangVaiTroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetBangVaiTroActionPerformed
        // TODO add your handling code here:
        cbFiled.setSelectedIndex(0);
        txtValueVaiTro.setText("");
        updateComponents();
    }//GEN-LAST:event_btnResetBangVaiTroActionPerformed

    public void updateComponents() {
        //hien thi bang vai tro
        Vector<String> header = new Vector<>();
        header.add("Mã vai trò");
        header.add("Tên vai trò");
        tbModelVaiTro = new DefaultTableModel(null, header)
        {
            boolean[] canEdit = new boolean [] {
                false, false
            };
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        };
        tbVaiTro.setModel(tbModelVaiTro);
        for (VaiTroDTO tk: VaiTroBUS.getInstance().getList()) {
            Vector<String> row = new Vector<>();
            row.add(tk.getMaVaiTro()+"");
            row.add(tk.getTenVaiTro());
            tbModelVaiTro.addRow(row);
        }
        tbVaiTro.setRowHeight(24);
        tbVaiTro.getTableHeader().setFont(new java.awt.Font("Arial", 1, 14));
        TableColumn column = null;
        for (int i = 0; i < 2; i++) {
            column = tbVaiTro.getColumnModel().getColumn(i);
            DefaultTableCellRenderer cellRenderer = new DefaultTableCellRenderer();
            cellRenderer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            column.setCellRenderer(cellRenderer);
            if (i == 2) {
                column.setPreferredWidth(200);
            } else {
                column.setPreferredWidth(40);
            }
        }
        tbVaiTro.setModel(tbModelVaiTro);
 
        //display data in combobox
        cbFiled.removeAllItems();
        cbFiled.addItem(new MyComboboxItem("Tên vai trò", VaiTroBUS.TENVAITRO));
        cbFiled.addItem(new MyComboboxItem("Mã vai trò", VaiTroBUS.MAVAITRO));
        
        //display data in permission table
        tbQuyen.getTableHeader().setFont(new java.awt.Font("Arial", 1, 16));
        tbQuyen.setRowHeight(30);
        Vector<String> headerQuyen = new Vector<>();
        headerQuyen.add("Tên chức năng");
        headerQuyen.add("Thêm");
        headerQuyen.add("Sửa");
        headerQuyen.add("Xóa");
        Vector<Vector<Object>> tenQuyen = new Vector<>();
        for (ChucNangDTO chucnang: ChucNangBUS.getInstance().getList()) {
            Vector<Object> row = new Vector<>();
            row.add(chucnang);
            row.add(false);
            row.add(false);
            row.add(false);
            tenQuyen.add(row);
        }
        tbModelQuyen = new DefaultTableModel( 
            tenQuyen, headerQuyen
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        };
        tbQuyen.setModel(tbModelQuyen);
     }
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNhapExcel;
    private javax.swing.JButton btnResetBangChucNang;
    private javax.swing.JButton btnResetBangVaiTro;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimChucNang;
    private javax.swing.JButton btnTimVaiTro;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXuatExcel;
    private javax.swing.JComboBox<MyComboboxItem> cbFiled;
    private javax.swing.JPanel chucNangPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbQuyen;
    private javax.swing.JScrollPane tbScrollPane;
    private javax.swing.JTable tbVaiTro;
    private javax.swing.JPanel timkiemPanel;
    private javax.swing.JLabel title;
    private javax.swing.JTextField txtTenQuyen;
    private javax.swing.JTextField txtTenVaiTro;
    private javax.swing.JTextField txtValueVaiTro;
    // End of variables declaration//GEN-END:variables
    private DefaultTableModel tbModelVaiTro;
    private DefaultTableModel tbModelQuyen;
    
    private JFrame pFrame;
     
     public static void main(String args[]) {
        JFrame frame = new JFrame("Demo QLTK Panel");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setSize(1170, 800);
        frame.setLocationRelativeTo(null);
        frame.add(new DemoPhanQuyenPanel(frame));
        frame.setVisible(true);
     }
 }